export const adminSidemenu = [
  {
    name: "dashboard",
    displayName: "Dashboard",
    route: "",
    icon: "dashboard.svg",
    active: true,
    key: "1",
  },
  {
    name: "about-us",
    displayName: "About Us",
    route: "/about-us",
    icon: "about-us.svg",
    active: false,
    key: "2",
  },
  {
    name: "services",
    displayName: "Our Services",
    route: "/services",
    icon: "services.svg",
    active: false,
    key: "3",
  },
  {
    name: "case-study",
    displayName: "Case Studys",
    route: "/case-study",
    icon: "case-study.svg",
    active: false,
    key: "4",
  },
  {
    name: "contact-us",
    displayName: "Contact Us",
    route: "/contact-us",
    icon: "contact-us.svg",
    active: false,
    key: "5",
  },
  {
    name: "logout",
    displayName: "Logout",
    route: "/logout",
    icon: "logout.svg",
    active: false,
    key: "6",
  },
];
